name: appdenotas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.0.1
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_unote.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logounote.png
    - lib/assets/images/app_icon_unote.png
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-Italic.ttf
          style: italic